### ISSUE TITLE
Stripe Elements?

### ISSUE THREAD

**Issue by nuwanvc** [fuentesloic/nuxt-stripe#21]
Can I use stripe elements with this module?

**Comment by flozero** [comment]
Hey @nuwanvc hope you doing good. Could you provide some docs about it will try to have a look this weekend

**Comment by stevenhurth** [comment]
Yes, you can. Once you get a handle on the client side stripe instance, you can call .elements() on it.

The automatic typescript resolution doesn't work with the module, but I was able to do the following for types to properly resolve (some code removed for brevity)

`
import {Stripe, StripeElements} from "@stripe/stripe-js";

const stripe = useClientStripe() as Stripe;
const elements = ref<StripeElements | undefined>();

const init = async () => {
  const intent = await useSubscriptionApi().getPaymentIntent();

  elements.value = stripe.elements({
    clientSecret: intent.clientSecret
  });

  const paymentElement = elements.value.create("payment");
  paymentElement.mount("#payment-element");
}
`

**Comment by flozero** [comment]
Thank you @stevenhurth <3 

Closing this for now don't hesitate to re open if we are missing something

**Comment by nuwanvc** [comment]
@stevenhurth @flozero Thanks for taking time to help me with the issue. 
I will try your method.

**Comment by phillipmohr** [comment]
Thanks! I had to make to change a couple things to make it work:
`const stripe = useClientStripe() as Stripe;` to `const stripe = await useClientStripe() as Stripe;`

and

`elements.value = stripe.elements();` to `elements.value = stripe.value.elements();`

Otherwise it doesn't work for me. However, I'm still getting this typescript error for `stripe.value.elements()` `Property 'value' does not exist on type 'Stripe'.ts(2339)`. Is this a bug?

**Comment by samulefevre** [comment]
Hello, i used onNuxtReady to make it works. Only way i found.

**Comment by BenWaNH** [comment]
Someone could post a concrete, functionnal example to use element... ?
It's not really clear how to use module to display a payment form. I tried several examples, stripe is loading correctly in variable but when i use mount function from Stripe nothing seems happen :'(

**Comment by azoom-sidonie-abe** [comment]
Hello there
I'm getting the same error even with onNuxtReady
Has anyone solved this?
It will be much appreciated if I can get a help on this
Thanks
`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'elements')`

```
const stripe = await useClientStripe() as Stripe
const elements = ref<StripeElements | undefined>()

const collectAddress = async () => {
  const addressElement = elements.value?.getElement('address')
  if (addressElement) {
    const { complete, value } = await addressElement.getValue()
    if (complete) {
    // completed logic here
 
    }
  }
}
const init = async () => {
  const options = {
    mode: 'setup',
    currency: 'jpy',
  }

  elements.value = await stripe.value.elements(options)
  const addressElement = elements?.value?.create('address', {
    mode: 'billing',
  })

  addressElement?.mount('#payment-element')
}

onNuxtReady(async () => {
  await init()
})
```
