### ISSUE TITLE
bug: missing typescript support

### ISSUE THREAD

**Issue by Sandros94** [fuentesloic/nuxt-stripe#24]
Pretty much title says everything, in the current state there is almost no Typescript support.

**Comment by Sandros94** [comment]
Testing on a different machine it seems it could be a problem on my end, now I see other interfaces but not all.

Closing for now

**Comment by g1ronn1mo** [comment]
I had the same Problem:

```
import type { Stripe } from '@stripe/stripe-js';
const stripeClient = await useClientStripe() as Stripe;
```

Just init the stripe Client with the namespace Stripe. A bit anoying, but does the trick. Maybe this gets fixed.
