### ISSUE TITLE
docs: missing how to configure keys at runtime

### ISSUE THREAD

**Issue by Sandros94** [fuentesloic/nuxt-stripe#25]
Missing documentation on how to configure or edit `publishableKey` and `apiKey` at runtime.

**Comment by fuentesloic** [comment]
sorry for the late response @Sandros94 can you propose a PR?

**Comment by fuentesloic** [comment]
I just read this ... so closing https://github.com/fuentesloic/nuxt-stripe/pull/19

**Comment by Sandros94** [comment]
> I just read this ... so closing https://github.com/fuentesloic/nuxt-stripe/pull/19

Looks like I also forgot this one open
