### ISSUE TITLE
Best way to handle webhooks?

### ISSUE THREAD

**Issue by JMKelley** [fuentesloic/nuxt-stripe#26]
Great module, made setting up stripe 100x easier.

What's the best way to handle webhooks in your opinion?

Thanks

**Comment by flozero** [comment]
Hey @JMKelley sorry for the no answer I didn't get notified will check at my configs

Really happy to see you are liking the module ❤️ 

We had this discussion in this issue https://github.com/fuentesloic/nuxt-stripe/issues/14

The solution 1 suggested seems to be the recommended way to go in our opinion. Adding more stuff about it in the module seems to over engeneer the module when its easily possible to do the same without it

How do you feel about it ? 

We probably need to add a recommandation doc about it as you are not the first one who asked about it

**Comment by flozero** [comment]
Just an update will look at it next weekend

**Comment by flozero** [comment]
closing this one for now
