### ISSUE TITLE
Is this module still maintained ?

### ISSUE THREAD

**Issue by ColinEspinas** [fuentesloic/nuxt-stripe#27]
Hello,

Was looking around to implement Stripe with Nuxt and checking out this module. Seems like this was not updated for the last 6 months. 
During those 6 months there were several updates on the SDKs and APIs from Stripe.

Is there a benefit to use this instead of implementing those by hand with the updated versions?

Will this ever be updated again?

Have a wonderful day, Colin.

**Comment by hdwebpros** [comment]
Following...

**Comment by flozero** [comment]
Hey @ColinEspinas @hdwebpros.

Ok time to watch this repo. I didn't get notified. Yes the repo is maintain base on what user notify :)

Can you provide us some links about the updates you are mentioning and what points you would like to have in the package.

Thank you and again sorry we didn't answer faster. It is a tough year

**Comment by ColinEspinas** [comment]
Hello @flozero,

The main issue is that the Stripe SDKs this module is relying are way outdated (some even passed multiple major versions).

See https://github.com/stripe/stripe-js/releases/tag/v3.1.0 and https://github.com/stripe/stripe-node/releases/tag/v14.23.0 for the latest releases.

From what I remember the config types and values for the API version also are out of date and/or incorrect (tested this a long time ago so might need to get back on it). The default is using quite an old version: 2022-11-15.

All this and the fact that this issue took a few months to get an answer led me to implement my own based on this module in my "starter" project (https://github.com/ColinEspinas/starter). If this can help in anyway (I also have some updating to do on my side).

Have a great day, Colin.

**Comment by flozero** [comment]
I can understand the frustration. I don't why My notification was off for this project. Will update the package not this weekend but next weekend. 

Don't hesitate to contribute to this project any helps are really welcome

Thank you again for raising the frustration here. Its important for the community and totally legitimate ! 

Have a good weekend

**Comment by ColinEspinas** [comment]
I was not really asking because of frustration but more in an informative way. 

I can understand that maintaining code is not always easy as I myself have a few projects left unmaintained for a while now.

If you want I can try to open a PR to update this project. Wasn't very used to Stripe when I asked a few months back and didn't want to make any bad PR as those can be just a pain. But now that I've done it on my side this shouldn't be an issue.

Have a great day, Colin.

**Comment by flozero** [comment]
Thanks for your understanding !

There is no bad PRs if you have done something for next weekend not the one tomorrow but next one :). I will be happy to continue working on your PR. 

Thank you again its important to have people like you

**Comment by fuentesloic** [comment]
@ColinEspinas I'm guilty as well. I never received the notification too 🤔 Will check this 👍

**Comment by fuentesloic** [comment]
@ColinEspinas, @hdwebpros and folks, ... I'm closing this one per #29. Thanks @flozero 🚀
